application: smileynoise
version: 2
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /message/.*
  script: message.py
  login: required
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: .*
  script: not_found.py

