application: smileynoise-hrd
version: 4
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /
  script: main.py
- url: /view/.*
  script: message.py
- url: /message/view/.*
  script: message.py

- url: /message/.*
  script: message.py
  login: required
  
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: .*
  script: not_found.py

libraries:
- name: jinja2
  version: latest
