application: smileynoise
version: 4
runtime: python
api_version: 1

handlers:

- url: /
  script: main.py
- url: /view/.*
  script: message.py

- url: /message/.*
  script: message.py
  login: required
  
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: .*
  script: not_found.py

