application: smileynoise-hrd
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  script: main.application
- url: /view/.*
  script: message.application
- url: /message/view/.*
  script: message.application

- url: /message/.*
  script: message.application
  login: required
  
- url: /scripts
  static_dir: scripts
- url: /styles
  static_dir: styles
- url: .*
  script: not_found.application

